name: hypersindy
channels:
  - defaults
dependencies:
  - python=3.9
  - scipy
  - seaborn
  - tensorboard
  - matplotlib
  - scikit-learn
  - pandas
  - jupyterlab
  - pip
  - pip:
    - numpy
    - pysindy
    - tqdm
    - torch
    - torchvision